// <auto-generated />
using System;
using Betriebsmittelverwaltung.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Betriebsmittelverwaltung.Migrations.My
{
    [DbContext(typeof(MyContext))]
    [Migration("20210626110502_bestand1")]
    partial class bestand1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Betriebsmittelverwaltung.Models.Baustellenverwaltung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("beschreibung");

                    b.Property<string>("kurzname");

                    b.HasKey("Id");

                    b.ToTable("Baustellenverwaltung");
                });

            modelBuilder.Entity("Betriebsmittelverwaltung.Models.Bestandsverwaltung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Kaufdatum");

                    b.Property<int>("Typ");

                    b.Property<int>("Wartungsintervall");

                    b.HasKey("Id");

                    b.ToTable("Bestandsverwaltung");
                });
#pragma warning restore 612, 618
        }
    }
}
